# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'text.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntext.proto\x12\x0etextprocessing\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"%\n\x06\x45ntity\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\"n\n\x0cTextResponse\x12\x0e\n\x06tokens\x18\x01 \x03(\t\x12\x11\n\tsentences\x18\x02 \x03(\t\x12\x11\n\tsentiment\x18\x03 \x01(\t\x12(\n\x08\x65ntities\x18\x04 \x03(\x0b\x32\x16.textprocessing.Entity2Y\n\rTextProcessor\x12H\n\x0bProcessText\x12\x1b.textprocessing.TextRequest\x1a\x1c.textprocessing.TextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=30
  _globals['_TEXTREQUEST']._serialized_end=57
  _globals['_ENTITY']._serialized_start=59
  _globals['_ENTITY']._serialized_end=96
  _globals['_TEXTRESPONSE']._serialized_start=98
  _globals['_TEXTRESPONSE']._serialized_end=208
  _globals['_TEXTPROCESSOR']._serialized_start=210
  _globals['_TEXTPROCESSOR']._serialized_end=299
# @@protoc_insertion_point(module_scope)
