name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  PROCESSING_IMAGE_NAME: processing_service
  SERVING_IMAGE_NAME: serving_service

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Processing Service
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ github.actor }}/${{ env.PROCESSING_IMAGE_NAME }}:latest
          echo "Building $IMAGE"
          docker build -t $IMAGE -f processing_service/Dockerfile .
          docker push $IMAGE
      - name: Build and Push Serving Service
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ github.actor }}/${{ env.SERVING_IMAGE_NAME }}:latest
          echo "Building $IMAGE"
          docker build -t $IMAGE -f serving_service/Dockerfile .
          docker push $IMAGE
