name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Processing Service
        run: |
          # Convert repository name to lowercase for Docker tag
          IMAGE=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/processing_service:latest
          echo "Building $IMAGE"
          docker build -t $IMAGE ./processing_service
          docker push $IMAGE

      - name: Build and Push Serving Service
        run: |
          IMAGE=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/serving_service:latest
          echo "Building $IMAGE"
          docker build -t $IMAGE ./serving_service
          docker push $IMAGE
